module.exports.users = [{
        id: 1,
        Username: "NickHoke",
        Password: "1111",
        Email: "eggydoc@gmail.com",
        Birthday: "12/5/1990",
        FavoriteMovies: [],
    },
    {
        id: 2,
        Username: "KenGriffey",
        Password: "2424",
        Email: "thekid@yahoo.com",
        Birthday: "3/25/1975",
        FavoriteMovies: [],
    },
    {
        id: 3,
        Username: "RikSmits",
        Password: "5555",
        Email: "rsmits@gmail.com",
        Birthday: "4/23/1966",
        FavoriteMovies: [],
    },
];